sudo: false

langugage: node_js

node_js:
  - node

script:
  - npm run lint
  - npm run test:coverage

after_success:
  - codecov

notifications:
  - email: false

env:
  global:
    secure: PGTfcPlbsr1pfRop7pjg46XgZit4zvR61PkakEi99Z5NWDccdgPGmev4KDZ9GMVhEhB9MSwY95JFfT1ASpQVCE/Xrpmo59Uue3L5d4wBRZ/YLYjtkIJmIrQF+v9WO7TrmuALxxfJ7QKW/2741yum1hjVTlTEyfKF8PtMEi2sBUncKfs0Hfpq/H+seUuqZ/uz4iZAm7pW3aMtcFxrkb+8Vd1rQ8JfFNDJsYa/4XN2sVEVb8DIBJgM7yvNrxkcjbAnmo9y2h/tdkt8gMgecmRIEgJRFi2Al4zjOY5TxrHY40KaiP1OFvMEeYH/0Bb1BMt9/M4dE3wvJEeRUW9nWoJwRlV3xnq8L3k6S1Jhl94q8/y7i7uAP1o5HWNZRs06FMHlpxVLk7tiQcrxKQewAmRItfueTeUoTn6PF6BwipBHOSvKQKXg6ku5x9ANrfpf5uuTuQqPMy9yyWOUpjuk9BerlSDjsktEvYsDerpU6olMK2khaFSv7DGKLD4bywZXmXjaI5WQ1yihjsJilE/OYlhuaU+Di+lPfuO3O5t4L1V9s+tb+FtZEfOHHlUxfDBvbfoWqYAjKOtpCOSuYc0wEscBI8OuEUe9IPf4asYWppP8rRiUwhCjsgDrk4MWtF/b02zKR0dsUf2NIpkr/Q67JSDYypsAeyWhJzGUx0Ajlme+M50=
